title: Ravikiran Krishnaprasad
logo: /assets/img/ProfilePicSAP.png

# Use simple text for description; consider moving HTML/Markdown content to your index.md or other HTML files
description: >
  I'm a software developer passionate about exploring and adopting new tech.
  My GitHub is where I document my journey through coding, from experimenting with the latest frameworks to tackling real-world problems. I believe in clear, maintainable code and am always on the lookout for better ways to solve complex issues. Here, you'll find projects that reflect my commitment to continuous learning and improvement in the ever-evolving tech landscape.

theme: jekyll-theme-minimal
